- name: Put containerd template
  template: 
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    mode: 644

- name: "modprobe overlay"
  modprobe:
    name: overlay
    state: present

- name: "modprobe br_netfilter"
  modprobe:
    name: br_netfilter
    state: present

- name: Put kubernetes-cri template
  template: 
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: 644

- name: Reload sysctl
  shell: "sysctl --system"

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create directory containerd
  file: 
    path: /etc/containerd
    owner: root 
    group: root 
    mode: 0755 
    state: directory

- name: Configure containerd
  ansible.builtin.shell: containerd config default | tee /etc/containerd/config.toml

- name: Put crictl template
  template: 
    src: crictl.yaml
    dest: /etc/crictl.yaml
    mode: 644

- name: Restart containerd
  systemd:
    state: restarted
    daemon_reload: yes
    name: containerd

- name: Download and unzip cri-tools (v1.20.0)
  ansible.builtin.unarchive:
    src: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.20.0/crictl-v1.20.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Prevent kubeadm from being upgraded
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Prevent kubectl from being upgraded
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Prevent kubelet from being upgraded
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Put kubelet template
  template: 
    src: 0-containerd.conf
    dest: /etc/systemd/system/kubelet.service.d/0-containerd.conf
    mode: 644

- name: Reload configs
  systemd: daemon_reload=yes
